name: adaptive_ui_kit
description: "Platform-adaptive Flutter UI kit with automatic Glass (iOS/macOS) and Material (Android) design — adaptive dialogs, pickers, and more."
version: 0.1.1
homepage: https://github.com/knoordeveloperhub/adaptive_ui_kit
repository: https://github.com/knoordeveloperhub/adaptive_ui_kit
issue_tracker: https://github.com/knoordeveloperhub/adaptive_ui_kit/issues


environment:
  sdk: ^3.4.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
